# Site settings
title: "WinterMUD"
bye_message: "До встречи!"
baseurl: "/"
url: "https://wintermud.github.io/"
disqus: wintermud

# Header settings
nick: "tuor"
mail:
    domain: "mail"
    ext: "ru"
source_code:
    server: "github.com"
    nick: "wintermud"
blog:
    server: "wordpress.com"
    nick: "wintermud"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
